name: ps_points
channels:
- conda-forge
dependencies:
        - earthengine-api
        - pandas
        - black
        - matplotlib
        - seaborn
        - folium        
        - geemap
        - jupytext
        - jupyter
        - scikit-learn
        - pip
        - pip:
                - tensorflow

